/// The running build's version and commit, reported by
/// `KiwiDesk --version` and the `version` command.
///
/// Both fields are plain constants bumped by hand as part of
/// the release process (see `scripts/bump-version.sh`) rather
/// than generated by a build-tool plugin — SwiftPM prebuild
/// plugins cannot run on this project's CI toolchain (see the
/// note in `Package.swift`), and shelling out to `git` at
/// runtime would fail for an installed binary with no `.git`
/// nearby. `commit` is `"unknown"` for local/dev builds where
/// the bump script has not been run since the last commit.
public enum KiwiDeskVersion {
    /// Semantic version, bumped per release.
    public static let semantic = "0.1.0"

    /// Short commit SHA as of the last version bump.
    public static let commit = "unknown"

    /// `"0.1.0 (abc1234)"`, or just the version when the
    /// commit is unknown.
    public static var displayString: String {
        commit == "unknown"
            ? semantic
            : "\(semantic) (\(commit))"
    }
}
