// Emits /robots.txt at build time. Driven by Astro's `site`
// (SITE_URL) so the absolute `Sitemap:` line follows the
// pages.dev → custom-domain switch without a hand edit. The
// sitemap itself is `sitemap-index.xml`, generated by
// @astrojs/sitemap (auto-registered by Starlight).
import type { APIRoute } from "astro";

export const GET: APIRoute = ({ site }) => {
  const sitemap = new URL("/sitemap-index.xml", site).href;
  const body = [
    "User-agent: *",
    "Allow: /",
    "",
    `Sitemap: ${sitemap}`,
    "",
  ].join("\n");
  return new Response(body, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
};
